### PR TITLE
Feat/add typescript integration

### LINKED ISSUE #3: Typescript not supported
Hey! Nice extension!

That's an old necessity of mine to auto-complete .env.

I noticed that only javascript is supported(unfortunately), are you open for PR?

Maybe I can send a change for that.

### PR DESCRIPTION
**Pull request by hofstede-matheus**
closes #3
add the functionality to typescript while keeping the javascript files integration

### CODE REVIEW

**Comment by jpruliere** [comment]
sorry for the delay, looks all good to me :ok_hand:

**Comment by hofstede-matheus** [comment]
so... no new version for this feature?

**Comment by jpruliere** [comment]
s*** :sweat_smile: 

sorry man, I am fixing it this week.

**Comment by jpruliere** [comment]
release in the pipe, should be good any minute

**Pull request merged**
